_target_: pytorch_lightning.Trainer

gpus:
  - 1
max_epochs: 500
  # distributed_backend: ddp
progress_bar_refresh_rate: 1
benchmark: True
precision: 16
gradient_clip_val: 5.0
num_sanity_val_steps: 3
sync_batchnorm: True
accumulate_grad_batches: 12
# reload_dataloaders_every_epoch: True
# resume_from_checkpoint: ${model_dir}/epoch=17-step=16235.ckpt
