_target_: src.models.dpr_model.DPRModel

model:
  query_model: ${model_dir}/bert-base-swedish-cased
  save_query_model: ${model_dir}/query_model
  passage_model: ${model_dir}/bert-base-swedish-cased
  save_passage_model: ${model_dir}/passage_model
  dropout: 0.25
  
optimizer:
  type: torch.optim.Adam
  lr: 0.00003

scheduler:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2
