_target_: src.models.gen_model.SkosaGenModel

model:
  model_folder: birgermoell/swedish-gpt
  #model_folder: gpt2
  save_model_folder: ${model_dir}/saved_long_model
  modified_voc_len: 50400
  freeze_layers: 0

optimizer:
  type: torch.optim.Adam
  lr: 0.00003

scheduler:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2
