_target_: src.models.gen_model.SkosaGenModel

model:
  model_folder: ${model_dir}/skosa_model
  save_model_folder: ${model_dir}/saved_qa_model
  modified_voc_len: 50400
  freeze_layers: 6

optimizer:
  type: torch.optim.Adam
  lr: 0.0003

scheduler:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2
