_target_: src.datamodules.gen_datamodule.SkosaGenDataModule


data_loader:
  generate_new: True
  dataset: LongTextDataset
  generate_size: 50
  max_token_size: 512
  data_folder: ${data_dir}/swedish_pdf
  model_folder: birgermoell/swedish-gpt
  num_workers: 12
  batch_size: 2
  test_ratio: 0.2
  seed: 1234
  
