_target_: src.datamodules.gen_datamodule.SkosaGenDataModule


data_loader:
  generate_new: True
  generate_size: -1
  max_token_size: 512
  data_folder: ${data_dir}/skosa_data
  model_folder: ${model_dir}/skosa_model
  num_workers: 12
  batch_size: 2
  test_ratio: 0.2
  seed: 1234
  
