_target_: src.datamodules.gen_datamodule.SkosaGenDataModule


data_loader:
  dataset: LongTextDataset
  max_token_size: 128
  data_folder: ${data_dir}/swedish_pdf
  model_folder: ${model_dir}/long_text_generator
  num_workers: 12
  batch_size: 2
  test_ratio: 0.2
  seed: 1234
  
